/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Main;
import Model.CitraKeabuan;
import Model.CitraWarna;
import Model.Hasil;
import Model.Parameter;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.time.Duration;
import java.time.Instant;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author M.Hakim Amransyah
 */
public class Home extends javax.swing.JFrame {

    private Main main;
    private CitraWarna warna;
    private CitraKeabuan abu;
    
    public Home(Main main) {
        initComponents();
        this.main = main;
    }

    private Home() {
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        muat_gambar = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        grayscale = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        do_dwt = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        do_copy_move_det = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        do_copy_move_svd = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        width_img = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        height_img = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        size_img = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        file_name = new javax.swing.JLabel();
        result = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panel_img = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        log = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel38 = new javax.swing.JPanel();
        log_panel = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        progress = new javax.swing.JProgressBar();
        jPanel39 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        spinnerNn = new javax.swing.JSpinner();
        jPanel41 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        spinnerNf = new javax.swing.JSpinner();
        jPanel42 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        spinnerWidthOverlappedBlock = new javax.swing.JSpinner();
        jPanel43 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        spinnerHeightOverlappedBlock = new javax.swing.JSpinner();
        jPanel44 = new javax.swing.JPanel();
        saveParam = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tugas Akhir Fahri");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        jLabel1.setText("Deteksi Salin Pindah");

        jLabel2.setText("DWT-SVD");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(509, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(269, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Home", jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        menu.setBackground(new java.awt.Color(255, 51, 0));
        menu.setPreferredSize(new java.awt.Dimension(15, 549));
        menu.setLayout(new java.awt.BorderLayout());

        jPanel7.setPreferredSize(new java.awt.Dimension(300, 190));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel10.setMaximumSize(new java.awt.Dimension(2147483647, 100));
        jPanel10.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel10.setPreferredSize(new java.awt.Dimension(344, 100));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanel11.setMinimumSize(new java.awt.Dimension(100, 20));
        jPanel11.setPreferredSize(new java.awt.Dimension(329, 20));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel6.setBackground(new java.awt.Color(0, 153, 153));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Menu");
        jPanel11.add(jLabel6, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel10);

        jPanel8.setPreferredSize(new java.awt.Dimension(344, 60));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel12.setPreferredSize(new java.awt.Dimension(344, 20));
        jPanel12.setLayout(new java.awt.BorderLayout());

        muat_gambar.setText("Muat Gambar");
        muat_gambar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        muat_gambar.setFocusable(false);
        muat_gambar.setVerifyInputWhenFocusTarget(false);
        muat_gambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muat_gambarActionPerformed(evt);
            }
        });
        jPanel12.add(muat_gambar, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel12);

        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel13.setPreferredSize(new java.awt.Dimension(344, 20));
        jPanel13.setLayout(new java.awt.BorderLayout());

        grayscale.setText("Grayscale");
        grayscale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        grayscale.setEnabled(false);
        grayscale.setFocusPainted(false);
        grayscale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grayscaleActionPerformed(evt);
            }
        });
        jPanel13.add(grayscale, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel13);

        jPanel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel15.setPreferredSize(new java.awt.Dimension(344, 20));
        jPanel15.setLayout(new java.awt.BorderLayout());

        do_dwt.setText("DWT");
        do_dwt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        do_dwt.setEnabled(false);
        do_dwt.setFocusPainted(false);
        do_dwt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                do_dwtActionPerformed(evt);
            }
        });
        jPanel15.add(do_dwt, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel15);

        jPanel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel16.setPreferredSize(new java.awt.Dimension(344, 20));
        jPanel16.setLayout(new java.awt.BorderLayout());

        do_copy_move_det.setText("Deteksi Copy Move");
        do_copy_move_det.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        do_copy_move_det.setEnabled(false);
        do_copy_move_det.setFocusPainted(false);
        do_copy_move_det.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                do_copy_move_detActionPerformed(evt);
            }
        });
        jPanel16.add(do_copy_move_det, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel16);

        jPanel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel14.setPreferredSize(new java.awt.Dimension(344, 20));
        jPanel14.setLayout(new java.awt.BorderLayout());

        do_copy_move_svd.setText("Detect Copy Move + SVD");
        do_copy_move_svd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        do_copy_move_svd.setEnabled(false);
        do_copy_move_svd.setFocusPainted(false);
        do_copy_move_svd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                do_copy_move_svdActionPerformed(evt);
            }
        });
        jPanel14.add(do_copy_move_svd, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel14);

        jPanel7.add(jPanel8);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Image Properties", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 11))); // NOI18N
        jPanel9.setPreferredSize(new java.awt.Dimension(338, 30));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel18.setLayout(new javax.swing.BoxLayout(jPanel18, javax.swing.BoxLayout.LINE_AXIS));

        jPanel20.setPreferredSize(new java.awt.Dimension(50, 122));
        jPanel20.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Width");
        jLabel3.setPreferredSize(new java.awt.Dimension(50, 14));
        jPanel20.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel20);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel19.setMinimumSize(new java.awt.Dimension(50, 0));
        jPanel19.setPreferredSize(new java.awt.Dimension(50, 209));
        jPanel19.setLayout(new java.awt.BorderLayout());

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setLayout(new java.awt.BorderLayout());

        width_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel21.add(width_img, java.awt.BorderLayout.CENTER);

        jPanel19.add(jPanel21, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel19);

        jPanel17.add(jPanel18);

        jPanel22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel22.setLayout(new javax.swing.BoxLayout(jPanel22, javax.swing.BoxLayout.LINE_AXIS));

        jPanel23.setPreferredSize(new java.awt.Dimension(50, 122));
        jPanel23.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Height");
        jLabel4.setPreferredSize(new java.awt.Dimension(50, 14));
        jPanel23.add(jLabel4, java.awt.BorderLayout.CENTER);

        jPanel22.add(jPanel23);

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel24.setMinimumSize(new java.awt.Dimension(50, 0));
        jPanel24.setPreferredSize(new java.awt.Dimension(50, 209));
        jPanel24.setLayout(new java.awt.BorderLayout());

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setLayout(new java.awt.BorderLayout());

        height_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel25.add(height_img, java.awt.BorderLayout.CENTER);

        jPanel24.add(jPanel25, java.awt.BorderLayout.CENTER);

        jPanel22.add(jPanel24);

        jPanel17.add(jPanel22);

        jPanel26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel26.setLayout(new javax.swing.BoxLayout(jPanel26, javax.swing.BoxLayout.LINE_AXIS));

        jPanel27.setPreferredSize(new java.awt.Dimension(50, 122));
        jPanel27.setLayout(new java.awt.BorderLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("File Size");
        jLabel5.setPreferredSize(new java.awt.Dimension(50, 14));
        jPanel27.add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanel26.add(jPanel27);

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));
        jPanel28.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel28.setMinimumSize(new java.awt.Dimension(50, 0));
        jPanel28.setPreferredSize(new java.awt.Dimension(50, 209));
        jPanel28.setLayout(new java.awt.BorderLayout());

        jPanel29.setBackground(new java.awt.Color(255, 255, 255));
        jPanel29.setLayout(new java.awt.BorderLayout());

        size_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel29.add(size_img, java.awt.BorderLayout.CENTER);

        jPanel28.add(jPanel29, java.awt.BorderLayout.CENTER);

        jPanel26.add(jPanel28);

        jPanel17.add(jPanel26);

        jPanel30.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel30.setLayout(new javax.swing.BoxLayout(jPanel30, javax.swing.BoxLayout.LINE_AXIS));

        jPanel31.setPreferredSize(new java.awt.Dimension(50, 122));
        jPanel31.setLayout(new java.awt.BorderLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("File Name");
        jLabel7.setPreferredSize(new java.awt.Dimension(50, 14));
        jPanel31.add(jLabel7, java.awt.BorderLayout.CENTER);

        jPanel30.add(jPanel31);

        jPanel32.setBackground(new java.awt.Color(255, 255, 255));
        jPanel32.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel32.setMinimumSize(new java.awt.Dimension(50, 0));
        jPanel32.setPreferredSize(new java.awt.Dimension(50, 209));
        jPanel32.setLayout(new java.awt.BorderLayout());

        jPanel33.setBackground(new java.awt.Color(255, 255, 255));
        jPanel33.setLayout(new java.awt.BorderLayout());

        file_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel33.add(file_name, java.awt.BorderLayout.CENTER);

        jPanel32.add(jPanel33, java.awt.BorderLayout.CENTER);

        jPanel30.add(jPanel32);

        jPanel17.add(jPanel30);

        jPanel9.add(jPanel17, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel9);

        menu.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel4.add(menu);

        result.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        result.setPreferredSize(new java.awt.Dimension(300, 549));
        result.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel37.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel37.setPreferredSize(new java.awt.Dimension(383, 450));
        jPanel37.setLayout(new java.awt.BorderLayout());

        panel_img.setLayout(new java.awt.BorderLayout());
        jScrollPane2.setViewportView(panel_img);

        jPanel37.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel37);

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setPreferredSize(new java.awt.Dimension(383, 10));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Simpan Gambar");
        jPanel6.add(jButton1, java.awt.BorderLayout.LINE_START);

        jPanel5.add(jPanel6);

        result.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel4.add(result);

        log.setPreferredSize(new java.awt.Dimension(40, 549));
        log.setLayout(new java.awt.BorderLayout());

        jPanel34.setLayout(new javax.swing.BoxLayout(jPanel34, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel35.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Log Proses", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel35.setLayout(new java.awt.BorderLayout());

        jPanel38.setBackground(new java.awt.Color(255, 255, 255));
        jPanel38.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel38.setLayout(new java.awt.BorderLayout());

        log_panel.setBackground(new java.awt.Color(255, 255, 255));
        log_panel.setLayout(new javax.swing.BoxLayout(log_panel, javax.swing.BoxLayout.Y_AXIS));
        jPanel38.add(log_panel, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(jPanel38);

        jPanel35.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel34.add(jPanel35);

        jPanel36.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel36.setPreferredSize(new java.awt.Dimension(254, 55));

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(progress, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progress, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel34.add(jPanel36);

        log.add(jPanel34, java.awt.BorderLayout.CENTER);

        jPanel4.add(log);

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Dashboard", jPanel3);

        jPanel39.setLayout(new java.awt.GridLayout(5, 0, 0, 50));

        jPanel40.setLayout(new java.awt.GridLayout(1, 2));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Nn");
        jPanel40.add(jLabel8);

        spinnerNn.setModel(new javax.swing.SpinnerNumberModel(5, 2, null, 1));
        jPanel40.add(spinnerNn);

        jPanel39.add(jPanel40);

        jPanel41.setLayout(new java.awt.GridLayout(1, 0));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Nf");
        jPanel41.add(jLabel9);

        spinnerNf.setModel(new javax.swing.SpinnerNumberModel(50, 1, null, 1));
        jPanel41.add(spinnerNf);

        jPanel39.add(jPanel41);

        jPanel42.setLayout(new java.awt.GridLayout(1, 0));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Width Overlapped Block");
        jPanel42.add(jLabel10);

        spinnerWidthOverlappedBlock.setModel(new javax.swing.SpinnerNumberModel(7, 1, null, 1));
        jPanel42.add(spinnerWidthOverlappedBlock);

        jPanel39.add(jPanel42);

        jPanel43.setLayout(new java.awt.GridLayout(1, 0));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Height Overlapped Block");
        jPanel43.add(jLabel11);

        spinnerHeightOverlappedBlock.setModel(new javax.swing.SpinnerNumberModel(7, 1, null, 1));
        jPanel43.add(spinnerHeightOverlappedBlock);

        jPanel39.add(jPanel43);

        jPanel44.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        saveParam.setText("Simpan Parameter");
        jPanel44.add(saveParam);

        jPanel39.add(jPanel44);

        jTabbedPane2.addTab("Parameter", jPanel39);

        jPanel1.add(jTabbedPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void muat_gambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muat_gambarActionPerformed
        CitraWarna citra = this.main.muatGambar();
        if(citra != null){
           this.warna = citra;
           JLabel img = new JLabel(new ImageIcon(citra.getImg()));
           this.panel_img.removeAll();
           this.panel_img.add(img);
           this.setProperti();
           this.grayscale.setEnabled(true);
           this.do_copy_move_svd.setEnabled(false);
           this.do_dwt.setEnabled(false);
           this.do_copy_move_det.setEnabled(false);
           this.addTextToPanelLog("Memuat Gambar");
        }
    }//GEN-LAST:event_muat_gambarActionPerformed

    private void grayscaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grayscaleActionPerformed
        this.abu = this.main.do_graysacle(warna);
        this.panel_img.removeAll();
        this.panel_img.repaint();
        JLabel img = new JLabel(new ImageIcon(this.abu.getImg()));
        this.panel_img.add(img);
        this.panel_img.repaint();
        this.panel_img.revalidate();
        this.addTextToPanelLog("Grayscaling Gambar");
        this.do_copy_move_svd.setEnabled(true);
        this.do_dwt.setEnabled(true);
    }//GEN-LAST:event_grayscaleActionPerformed

    private void do_dwtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_do_dwtActionPerformed
        this.abu = this.main.dekomposisi(abu);
        this.panel_img.removeAll();
        this.panel_img.repaint();
        JLabel img = new JLabel(new ImageIcon(this.abu.getImg()));
        this.panel_img.add(img);
        this.do_copy_move_det.setEnabled(true);
        this.panel_img.repaint();
        this.panel_img.revalidate();
        this.addTextToPanelLog("Dekomposisi Gambar (DWT LL)");
        this.addTextToPanelLog("  Width   : "+this.abu.getKolom());
        this.addTextToPanelLog("  Height : "+this.abu.getBaris());
    }//GEN-LAST:event_do_dwtActionPerformed

    private void do_copy_move_detActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_do_copy_move_detActionPerformed
        this.addTextToPanelLog("Copy Move Detection");
        
        Parameter parameter = new Parameter(
            (int)this.spinnerNn.getValue(),
            (int)this.spinnerNf.getValue(),
            (int)this.spinnerWidthOverlappedBlock.getValue(),
            (int)this.spinnerHeightOverlappedBlock.getValue()
        );
        
        Instant startTime = Instant.now();
        Hasil hasil = this.main.detectCopyMove(abu, parameter, false);                
        Instant endTime = Instant.now();
        
        Duration durasi = Duration.between(startTime, endTime);
        
        this.panel_img.removeAll();
        this.panel_img.repaint();
        JLabel img = new JLabel(new ImageIcon(hasil.getCitra().getImg()));
        this.panel_img.add(img);
        
        this.panel_img.repaint();
        this.panel_img.revalidate();        
        
        this.addTextToPanelLog("  jumlah objek terdeteksi : " +hasil.getDetectedObjectCount());
        this.addTextToPanelLog("  durasi : " +durasi.getSeconds());
    }//GEN-LAST:event_do_copy_move_detActionPerformed

    private void do_copy_move_svdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_do_copy_move_svdActionPerformed
        
        this.addTextToPanelLog("Copy Move Detection");
        
        Parameter parameter = new Parameter(
            (int)this.spinnerNn.getValue(),
            (int)this.spinnerNf.getValue(),
            (int)this.spinnerWidthOverlappedBlock.getValue(),
            (int)this.spinnerHeightOverlappedBlock.getValue()
        );
        
        Instant startTime = Instant.now();
        Hasil hasil = this.main.detectCopyMove(abu, parameter, true);                
        Instant endTime = Instant.now();
        
        Duration durasi = Duration.between(startTime, endTime);
        
        this.panel_img.removeAll();
        this.panel_img.repaint();
        JLabel img = new JLabel(new ImageIcon(hasil.getCitra().getImg()));
        this.panel_img.add(img);
        
        this.panel_img.repaint();
        this.panel_img.revalidate();        
        
        this.addTextToPanelLog("  jumlah objek terdeteksi : " +hasil.getDetectedObjectCount());
        this.addTextToPanelLog("  durasi : " +durasi.getSeconds()+ " s");
    }//GEN-LAST:event_do_copy_move_svdActionPerformed

    private void setProperti(){
        this.width_img.setText(this.warna.getKolom()+"");
        this.height_img.setText(this.warna.getBaris()+"");
        this.file_name.setText(this.warna.getNama_file());
        this.size_img.setText(this.warna.getSize()+"");
    }
    
    private void addTextToPanelLog(String text){
        JLabel label =new JLabel(" "+text);
        label.setFont(new Font("CenturyGothic",Font.PLAIN,12));
        this.log_panel.add(label);
        this.log_panel.revalidate();
        this.log_panel.repaint();
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton do_copy_move_det;
    private javax.swing.JButton do_copy_move_svd;
    private javax.swing.JButton do_dwt;
    private javax.swing.JLabel file_name;
    private javax.swing.JButton grayscale;
    private javax.swing.JLabel height_img;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel log;
    private javax.swing.JPanel log_panel;
    private javax.swing.JPanel menu;
    private javax.swing.JButton muat_gambar;
    private javax.swing.JPanel panel_img;
    private javax.swing.JProgressBar progress;
    private javax.swing.JPanel result;
    private javax.swing.JButton saveParam;
    private javax.swing.JLabel size_img;
    private javax.swing.JSpinner spinnerHeightOverlappedBlock;
    private javax.swing.JSpinner spinnerNf;
    private javax.swing.JSpinner spinnerNn;
    private javax.swing.JSpinner spinnerWidthOverlappedBlock;
    private javax.swing.JLabel width_img;
    // End of variables declaration//GEN-END:variables
}
